### PR TITLE
add “Free Culture” presentation by Lawrence Lessig

### PR DESCRIPTION
**Pull request by ousia**
Add an excellent _Flash_ presentation: a classic from 2002, thanks to Leonard Lin.

Just in case you wonder, this was created before _YouTube_ was born.

### CODE REVIEW

**Comment by ousia** [comment]
I just force pushed to close ruffle-rs/ruffle#1629.

I’ve just amended the commit message.

**Comment by Herschel** [comment]
Looks like this commit is missing the actual SWF file.

**Comment by ousia** [comment]
Sorry, I simply forgot it 🤦‍♂️.

**Comment by Herschel** [comment]
Yikes, I guess the auto-build does interfere with this (force push makes the history change, so it invalidates the PR). I'll have to see if there's a better way to accomplish this.

**Comment by ousia** [comment]
With this particular presentation, I forgot (as @parkerlreed noticed) that `Sound.position()` is required to pause and unpause the presentation (ruffle-rs/ruffle#340).

So, we will have to wait until this feature is implemented in Ruffle. Once it’s done, I will submit another PR (without force-pushing it).

**Pull request closed without merging**
